name: Rust Build and Package

on:
  push:
    branches:
      - release/**
    tags:
      - v*

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: SebRollen/toml-action@v1.2.0
        id: get_cargo_package_name
        with:
          file: 'Cargo.toml'
          field: 'package.name'

      - uses: SebRollen/toml-action@v1.2.0
        id: get_cargo_package_version
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Set filenames as Env variable
        run: |
          $target = "x86_64-pc-windows-msvc"
          echo "TARGET=$target" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SRC_FILENAME=${{ steps.get_cargo_package_name.outputs.value }}-${{ github.ref_name }}-source.zip" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "RLS_FILENAME=fp.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "RLS_ZIP_NAME=vfp-${{ github.ref_name }}-$target.zip" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Print Env variable
        run: |
          echo "TARGET: ${{env.TARGET}}"
          echo "SRC_FILENAME: ${{env.SRC_FILENAME}}"
          echo "RLS_FILENAME: ${{env.RLS_FILENAME}}"
          echo "RLS_ZIP_NAME: ${{env.RLS_ZIP_NAME}}"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{env.TARGET}}
          default: true

      - name: Build
        env:
          CHECK_EXE_FILE_NAME: ${{ secrets.CHECK_EXE_FILE_NAME}}
          EXE_FILE_NAME: ${{ secrets.EXE_FILE_NAME}}
          JENKINS_URL: ${{ secrets.JENKINS_URL}}
          LOCATOR_PATTERN: ${{ secrets.LOCATOR_PATTERN}}
          LOCATOR_TEMPLATE: ${{ secrets.LOCATOR_TEMPLATE}}
          MENDING_FILE_PATH: ${{ secrets.MENDING_FILE_PATH}}
          PACKAGE_FILE_STEM: ${{ secrets.PACKAGE_FILE_STEM}}
          RECOMMEND_JOB_NAMES: ${{ secrets.RECOMMEND_JOB_NAMES}}
          REPO_TEMPLATE: ${{ secrets.REPO_TEMPLATE}}
        run: cargo build --release --target ${{env.TARGET}}

      - name: Package into zip
        run: |
          mkdir release-dir
          copy ./target/${{env.TARGET}}/release/${{ steps.get_cargo_package_name.outputs.value }}.exe release-dir\
          Compress-Archive -Path release-dir\* -DestinationPath ${{env.RLS_ZIP_NAME}}

      - name: Archive source code
        run: git archive -o ${{env.SRC_FILENAME}} HEAD

      - name: Upload release binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: ./target/${{env.TARGET}}/release/${{ steps.get_cargo_package_name.outputs.value }}.exe

      - name: Upload source code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: ${{env.SRC_FILENAME}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.get_cargo_package_name.outputs.value }} ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{env.RLS_ZIP_NAME}}
          asset_name: ${{env.RLS_ZIP_NAME}}
          asset_content_type: application/zip

      - name: Upload Source Code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{env.SRC_FILENAME}}
          asset_name: ${{env.SRC_FILENAME}}
          asset_content_type: application/zip