// Auto Generated by build.rs
pub const REPO_TEMPLATE: &str = "";
pub const LOCATOR_PATTERN: &str = "";
pub const LOCATOR_TEMPLATE: &str = "";
pub const MENDING_FILE_PATH: &str = "";

pub const PACKAGE_FILE_STEM: &str = "";
pub const EXE_FILE_NAME: &str = "";
pub const CHECK_EXE_FILE_NAME: &str = "";
