// Auto Generated by build.rs. Do not edit it manually.
// Used for sensitive data injection.

pub const COUNT: u32 = 4;
pub const RUN_COUNT: u32 = 1;
pub const WATCH_INTERVAL: u64 = 10;
pub const WATCH_QUERY_BUILDS_COUNT: u32 = 10;
pub const OLDEST_SUPPORT_UPDATE_VERSION: &str = "1.5.0";
pub const MAX_JOB_RELATIVE_DATA_COUNT: usize = 8;
pub const USER_QUERY_JENKINS_BUILD_COUNT: usize = 50;
pub const JENKINS_QUERY_CONCURRENCY_COUNT: usize = 20;

pub const RECOMMEND_JOB_NAMES: [&str; 0] = [
];

pub const REPO_TEMPLATE: &str = "";
pub const LOCATOR_PATTERN: &str = "";
pub const LOCATOR_TEMPLATE: &str = "";
pub const MENDING_FILE_PATH: &str = "";

pub const RELEASE_URL: &str = "https://github.com/LviatYi/vertical-fire-platform/releases/tag/v";

pub const PACKAGE_FILE_STEM: &str = "";
pub const EXE_FILE_NAME: &str = "";
pub const CHECK_EXE_FILE_NAME: &str = "";

pub const JENKINS_URL: &str = "";

pub const QUERY_TOKEN_GITHUB: &str = "";
